import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>My Next Movie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="author" content="Guilherme Daniel" />
        <meta name="description" content="Made with next.js" />
      </Head>
      <main>
        <h1>My next movie</h1>
      </main>
    </>
  );
}
